"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: 
  IDL file: rt_inspire_cmd.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

from atom.msg.dds_ import *



@dataclass
@annotate.final
@annotate.autoid("sequential")
class HandsCmd_(idl.IdlStruct, typename="dobot_atom.msg.dds_.HandsCmd_"):
    hands: types.array['MotorCmd_', 12]


