"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: 
  IDL file: rt_lower_state.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

from atom.msg.dds_ import *


@dataclass
@annotate.final
@annotate.autoid("sequential")
class LowerState_(idl.IdlStruct, typename="dobot_atom.msg.dds_.LowerState_"):
    fsm_id: types.uint16
    imu_state: 'IMUState_'
    motor_state: types.array['MotorState_', 12]
    bms_state: 'BmsState_'
    wireless_remote: types.array[types.uint8, 40]
    reserve: types.uint32


