"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.10.5
  Module: 
  IDL file: rt_upper_state.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

from atom.msg.dds_ import *

@dataclass
@annotate.final
@annotate.autoid("sequential")
class UpperState_(idl.IdlStruct, typename="dobot_atom.msg.dds_.UpperState_"):
    robot_type: types.array[types.char, 16]
    is_upper_control: bool
    fsm_id: types.uint16
    motor_state: types.array['MotorState_', 17]
    bms_state: 'BmsState_'
    wireless_remote: types.array[types.uint8, 40]
    reserve: types.uint32


